name: Deploy AWS Lambda   # Name of the workflow

on: 
  push:
    branches:
      - main
    # paths:
    #   - 'lambda-cicd/**'

env:
  ACTIONS_STEP_DEBUG: true

jobs:       # Jobs to run inside workflow
  deploy-lambda:          # Name of the job
    runs-on: ubuntu-latest    # Specifies the runner
    steps: 
      - uses: actions/checkout@v3

      - name: Set Up Python   # Sets up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies  # Installs packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS credentials   # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Lambda Function    # Zips lambda directory and updates the function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
